In [573]:
!pip install datasets


In [574]:
from datasets import load_dataset

In [575]:
dataset=load_dataset("CShorten/ML-ArXiv-Papers",split="train")

In [576]:
dataset[0]

{'Unnamed: 0.1': 0,
 'Unnamed: 0': 0.0,
 'title': 'Learning from compressed observations',
 'abstract': '  The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rat

In [577]:
import pandas as pd

In [578]:
df=pd.DataFrame(dataset)
df

,Unnamed: 0.1,Unnamed: 0,title,abstract
0,0,0.0,Learning from compressed observations,The problem of statistical learning is to co...
1,1,1.0,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,2,2.0,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,3,3.0,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,4,4.0,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...,...,...
117587,4995,NaN,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,4996,NaN,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,4997,NaN,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,4998,NaN,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."


In [579]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'], dtype='object')

In [580]:
df = df[['title','abstract']].copy()

In [581]:
df

,title,abstract
0,Learning from compressed observations,The problem of statistical learning is to co...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...
117587,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."


In [582]:
df.shape

(117592, 2)

In [583]:
df = df.head(15000).copy()

In [584]:
df.shape

(15000, 2)

In [585]:
df.isnull().sum()

,0
title,0
abstract,0


In [586]:
df["paper_text"]=df["title"]+" "+df["abstract"]

In [587]:
df[["paper_text"]].head()

,paper_text
0,Learning from compressed observations The pr...
1,Sensor Networks with Random Links: Topology De...
2,The on-line shortest path problem under partia...
3,A neural network approach to ordinal regressio...
4,Parametric Learning and Monte Carlo Optimizati...


In [588]:
type(df[["paper_text"]])

pandas.core.frame.DataFrame

In [589]:
df[["paper_text"]].head()

,paper_text
0,Learning from compressed observations The pr...
1,Sensor Networks with Random Links: Topology De...
2,The on-line shortest path problem under partia...
3,A neural network approach to ordinal regressio...
4,Parametric Learning and Monte Carlo Optimizati...


In [590]:
print(df["paper_text"].iloc[0])

Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to approach
asymptotically the performance (expected loss) of the best predictor in the
class. We consider the setting in which one has perfect observation of the
$X$-part of the sample, while the $Y$-part has to be communicated at some
finite bit rate. The encoding of the $Y$-values is allowed to depend on the
$X$-values. Under suitable regularity conditions on the admissible predictors,
the underlying family of probability distributions and the loss function, we
give an information-theoretic characterization of achievable predictor
performance in terms of conditional distortion-rate functions. The ideas are
illustrated on the example of nonparametric regress

In [591]:
from sentence_transformers import SentenceTransformer

In [592]:
model=SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [593]:
print(type(model))

<class 'sentence_transformers.sentence_transformer.model.SentenceTransformer'>


In [594]:
df["paper_text"] = df["paper_text"].str.replace("\n","",regex=False)
df["paper_text"] = df["paper_text"].str.strip()

In [595]:
sample_text=df["paper_text"].iloc[0]
sample_text

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a randomvariable $Y$ as a function of a related random variable $X$ on the basis of ani.i.d. training sample from the joint distribution of $(X,Y)$. Allowablepredictors are drawn from some specified class, and the goal is to approachasymptotically the performance (expected loss) of the best predictor in theclass. We consider the setting in which one has perfect observation of the$X$-part of the sample, while the $Y$-part has to be communicated at somefinite bit rate. The encoding of the $Y$-values is allowed to depend on the$X$-values. Under suitable regularity conditions on the admissible predictors,the underlying family of probability distributions and the loss function, wegive an information-theoretic characterization of achievable predictorperformance in terms of conditional distortion-rate functions. The ideas areillustrated on the example of nonparametric regression in Gaus

In [596]:
embedding=model.encode(sample_text)
print(type(embedding))
print(embedding.shape)

<class 'numpy.ndarray'>
(384,)


In [597]:
embedding[:56]

array([-0.12687647, -0.02378245, -0.00790563,  0.02424844,  0.1218068 ,
        0.03128361,  0.0832822 , -0.09455425,  0.03418481, -0.0151784 ,
       -0.02046121,  0.08573572,  0.10659824, -0.01521946, -0.01140681,
       -0.01369359,  0.06911204,  0.05154104, -0.09823959,  0.03143351,
        0.08310774,  0.02582335,  0.02238519,  0.04544116,  0.09216702,
       -0.09331413,  0.02776143, -0.01132281, -0.03970057, -0.00274548,
       -0.03780857, -0.05089735, -0.00553847, -0.024204  ,  0.0238256 ,
        0.02581022,  0.03212146,  0.05139888,  0.04338713,  0.04737513,
       -0.03348187, -0.00359935, -0.02396433,  0.02307127, -0.0061548 ,
        0.02532698,  0.06171655, -0.02783949, -0.06917551,  0.05014006,
       -0.02832331,  0.07954925, -0.04605051,  0.00583216,  0.02012847,
       -0.02504408], dtype=float32)

In [598]:
sample_embedding=model.encode(df['paper_text'].head(5).to_list())

In [599]:
print(sample_embedding.shape)

(5, 384)


In [600]:
from sklearn.metrics.pairwise import cosine_similarity

In [601]:
similarity=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[0].reshape(1,-1))
print(similarity)

[[1.]]


In [602]:
similarity=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[1].reshape(1,-1))
print(similarity)

[[0.32237816]]


In [603]:
for i in range(1,5):
  sim=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[i].reshape(1,-1))
  print(similarity)

[[0.32237816]]
[[0.32237816]]
[[0.32237816]]
[[0.32237816]]


Generate full embedding


In [604]:
import os
import numpy as np
if os.path.exists("paper_embeddings.npy"):
  print("loading existing embeddings")
  embeddings=np.load("paper_embeddings.npy")
else:
  print("creating new embeddings")
  embeddings=model.encode(df["paper_text"].to_list(),batch_size=32,show_progress_bar=True)
  np.save("paper_embeddings.npy",embeddings)
  print("embeddings created successfully")

loading existing embeddings


In [605]:
print(embedding.shape)
print(type(embedding))

(384,)
<class 'numpy.ndarray'>


In [606]:
print("Verifying embedding shape before faiss.normalize_L2:")
print(f"Embedding shape: {embedding.shape}")
print(f"Embedding type: {type(embedding)}")

Verifying embedding shape before faiss.normalize_L2:
Embedding shape: (384,)
Embedding type: <class 'numpy.ndarray'>


In [607]:
embedding.dtype

dtype('float32')

In [608]:
!pip install faiss-cpu

In [609]:
import faiss

In [610]:
#faiss.normalize_L2(embedding)

In [611]:
#index= faiss.IndexFlatIP(384)

In [612]:
#index.add(embedding)

In [613]:
if os.path.exists("paper_faiss.index"):
  print("loading existing Faiss index")
  index=faiss.read_index("paper_faiss.index")
else:
  print("creating new Faiss index")
  faiss.normalize_L2(embedding)
  index=faiss.IndexFlatIP(384)
  index.add(embedding)
  faiss.write_index(index,"paper_faiss.index")
  print("Faiss index created successfully")

loading existing Faiss index


In [614]:
print(index.ntotal)

15000


In [615]:
query="deep learning for medical image analysis"
query_embedding=model.encode([query])
query_embedding.shape

(1, 384)

In [616]:
faiss.normalize_L2(query_embedding)

In [617]:
D,I=index.search(query_embedding,5)
print(D)
print(I)

[[0.6664674  0.6369015  0.6360254  0.6353009  0.62213373]]
[[10466 12691 11873 13730  7818]]


In [618]:
print(df.iloc[10466]["title"])

A Perspective on Deep Imaging


In [619]:
print(df.iloc[12691]["title"])

High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks


In [620]:
def search_paper(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  return D,I

In [621]:
D,I=search_paper("deep learning for medical image analysis")
print(D)
print(I)

[[0.6664674  0.6369015  0.6360254  0.6353009  0.62213373]]
[[10466 12691 11873 13730  7818]]


In [622]:
def search_paper(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  for score,idx in zip(D[0],I[0]):
    print("Title:" ,df.iloc[idx]['title'])
    print("Similarity Score:" ,score)
    print("title", df.iloc[idx]['abstract'][:500])

In [623]:
search_paper("deep learning for medical image analysis")

Title: A Perspective on Deep Imaging
Similarity Score: 0.6664674
title   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance
Title: High-Resolution Breast Cancer Screening with Multi-View Deep
  Convolutional Neural Networks
Similarity Score: 0.6369015
title   Advances in deep learning for natural images have prompted a surge of
interest in applying similar techniques to medical images. The majority of the
initial attempts focused on replacing the input of a deep convolutional neural
network with a medical image, which does not take into considera

In [624]:
!pip install transformers

In [625]:
!pip uninstall -y transformers tokenizers
!pip install transformers
from transformers import pipeline

Found existing installation: transformers 5.13.0
Uninstalling transformers-5.13.0:
  Successfully uninstalled transformers-5.13.0
Found existing installation: tokenizers 0.22.2
Uninstalling tokenizers-0.22.2:
  Successfully uninstalled tokenizers-0.22.2
  Using cached transformers-5.13.0-py3-none-any.whl.metadata (32 kB)
  Using cached tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Using cached transformers-5.13.0-py3-none-any.whl (11.5 MB)
Using cached tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)


In [649]:

from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import faiss

embedding_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

# Define the summarization tokenizer and model (used for generating summaries)
summarization_tokenizer = AutoTokenizer.from_pretrained("facebook/bart-large-cnn")
summarization_model = AutoModelForSeq2SeqLM.from_pretrained("facebook/bart-large-cnn")

def search_paper(query, k=5):
    query_embedding = embedding_model.encode([query])
    faiss.normalize_L2(query_embedding)
    D, I = index.search(query_embedding, k)
    return D, I

def summarizer_search(query, k=5):
    D, I = search_paper(query, k)
    for score, idx in zip(D[0], I[0]):
        paper_title = df.iloc[idx]['title']
        paper_abstract = df.iloc[idx]['abstract']

        # Generate summary for the abstract using the summarization model
        inputs = summarization_tokenizer([paper_abstract], max_length=1024, return_tensors='pt', truncation=True)
        summary_ids = summarization_model.generate(
            inputs['input_ids'],
            num_beams=4,
            max_length=150,
            min_length=30,
            early_stopping=True
        )
        generated_summary = summarization_tokenizer.decode(summary_ids[0], skip_special_tokens=True)

        print(f"\n--- Search Result (Score: {score:.4f}) ---")
        print(f"Title: {paper_title}")
        print(f"Abstract: {paper_abstract[:500]}...")
        print(f"Summary: {generated_summary}")

summarizer_search("deep learning for medical image analysis", k=3)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/511 [00:00<?, ?it/s]


--- Search Result (Score: 0.6665) ---
Title: A Perspective on Deep Imaging
Abstract:   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance...
Summary: The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image                reconstruction. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical andpreclinical applications.

--- Search Result (Score: 0.63

KeyBERT Analysis

In [641]:
pip install keybert==0.8.5

In [642]:
from keybert import KeyBERT
kw_model = KeyBERT()

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [644]:
text= df.iloc[10466]["abstract"]
keywords = kw_model.extract_keywords(text)
print (keywords)

[('imaging', 0.4528), ('tomographic', 0.4488), ('reconstruction', 0.3623), ('deep', 0.3003), ('learning', 0.2622)]


In [645]:
keywords=kw_model.extract_keywords(text, keyphrase_ngram_range=(1, 3), stop_words=None)
print(keywords)

[('imaging and deep', 0.5798), ('medical imaging to', 0.5289), ('image reconstruction the', 0.5288), ('medical imaging', 0.5281), ('tomographic imaging', 0.525)]


Named Entity Recognition (NER)


In [650]:
from transformers import pipeline

# Initialize the NER pipeline
ner_pipeline = pipeline("ner", model="dslim/bert-base-NER")
print("NER pipeline initialized successfully.")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: dslim/bert-base-NER
Key                      | Status     |  | 
-------------------------+------------+--+-
bert.pooler.dense.bias   | UNEXPECTED |  | 
bert.pooler.dense.weight | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


NER pipeline initialized successfully.


In [655]:
sample_title_for_ner = df.iloc[10466]["title"]
print("--- Sample Title ---")
print(sample_title_for_ner)

# Perform NER on the title
ner_results_title = ner_pipeline(sample_title_for_ner)

print("\n--- NER Results for Title ---")
if ner_results_title:
    for entity in ner_results_title:
        print(f"Entity: {entity['word']}, Type: {entity['entity']}, Score: {entity['score']:.4f}")
else:
    print("No named entities found in the title.")

--- Sample Title ---
A Perspective on Deep Imaging

--- NER Results for Title ---
Entity: Deep, Type: B-ORG, Score: 0.6267
Entity: I, Type: I-ORG, Score: 0.8255
Entity: ##maging, Type: I-MISC, Score: 0.6000


Langchain


In [661]:
pip install langchain-community langchain-core

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 29.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 43.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 3.9 MB/s eta 0:00:00
  Attempting uninstall: requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.


In [659]:
from langchain_core.tools import tool

In [675]:
@tool
def search_paper(query:str)-> str:
  "Search research paper from ther faiss database and return the most relevant result"

In [674]:
pip install langchain-community langchain-core langchain-huggingface

In [664]:
from langchain_huggingface import HuggingFacePipeline

In [670]:
llm=HuggingFacePipeline( pipeline=summarization_model)

In [671]:
llm

HuggingFacePipeline(metadata={'lc_versions': {'langchain-core': '1.4.8', 'langchain': '1.3.11'}}, pipeline=BartForConditionalGeneration(
  (model): BartModel(
    (shared): BartScaledWordEmbedding(50264, 1024, padding_idx=1)
    (encoder): BartEncoder(
      (embed_tokens): BartScaledWordEmbedding(50264, 1024, padding_idx=1)
      (embed_positions): BartLearnedPositionalEmbedding(1026, 1024)
      (layers): ModuleList(
        (0-11): 12 x BartEncoderLayer(
          (self_attn): BartAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (activation_fn): GELUActivation()
          (fc1): Linear(in_features=1024, out